
language: go
sudo: false
go:
- 1.10
install:
- go get github.com/shurcooL/vfsgen
- go get -v -t
script:
- go test -v
after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
